apiVersion: v1
kind: Service
metadata:
  name:  edge-envoy
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    run: edge-envoy
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  80
---
#apiVersion: apps/v1 #v1.9.x
apiVersion: extensions/v1beta1 #v1.8.x
kind: Deployment
metadata:
  name: edge-envoy
  labels:
    run: edge-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: edge-envoy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: edge-envoy
    spec:
      containers:
      # Edge Envoy Proxy Container
      - image: envoyproxy/envoy-alpine:latest
        command: 
          - "/usr/local/bin/envoy"
        args:
          - "--config-path /etc/envoy/envoy.json"
          - "--mode serve"
        imagePullPolicy: Always
        name: edge-envoy
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: edge-envoy-config
          mountPath: /etc/envoy
        - name: edge-envoy-rt-config
          mountPath: /srv/runtime/envoy/routing/ts/node-app
      volumes:
      - name: edge-envoy-config
        configMap:
          name: edge-envoy-config
      - name: edge-envoy-rt-config
        configMap:
          name: edge-envoy-rt-config